name: Upload Extended Data to Dune

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 */6 * * *"    # кожні 6 годин
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Fetch Extended API data
      run: |
        echo "🚀 Fetching data from Extended API..."
        python fetch_data_to_dune.py
        
    - name: Show uploads directory
      run: |
        echo "📁 Contents of uploads directory:"
        ls -la uploads/ || echo "uploads/ directory not found"
        if [ -f uploads/extended_markets_data.csv ]; then
          echo "📊 CSV file size:"
          wc -l uploads/extended_markets_data.csv
        fi
        
    - name: Upload CSVs to Dune
      env:
        DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
      run: |
        echo "⬆️ Uploading to Dune Analytics..."
        python scripts/upload_to_dune.py
